# Generated by Django 4.2.4 on 2023-10-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_image', models.ImageField(upload_to='cat_photos')),
                ('category_name', models.CharField(max_length=25, unique=True)),
                ('brand', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
